### ISSUE TITLE
Catalog demo Styles?

### ISSUE THREAD

**Issue by dorohinsa** [Alexander96196/arsenal#1]
@Alexander96196  Тут что то нужно было убрать?

.catalog-detail-page .price {
  display: block;
  /* Демонстрационный вариант, убрать при добавление в проект */
  font: 700 24px/30px Arial, sans-serif;
  color: #333;
}

**Comment by Alexander96196** [comment]
Display: block убрать. Я просто развернул для показа, как выглядит данный блок.
